name: Tag Docker image as latest

on: workflow_dispatch

env:
  TIDYVERSE_VERSION: 4.3.1
  FAASR_VERSION: 1.1.2
  TAG_SUFFIX: rel
  GHCR_IO_REPO: faasr
  AWS_REGION: us-east-1
  FAASR_TAG: 1.1.2

permissions: write-all

jobs:
  tag-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2  
      - name: Pull openwhisk-tidyverse Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/openwhisk-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} 
      - name: Tag and push openwhisk-tidyverse Docker image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/openwhisk-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} ${{ secrets.DOCKERHUB_USERNAME }}/openwhisk-tidyverse:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/openwhisk-tidyverse:latest
      - name: Pull github-actions-tidyverse Github Container registry image
        run: |
          docker pull ghcr.io/${{ env.GHCR_IO_REPO }}/github-actions-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} 
      - name: Tag and push github-actions-tidyverse Github Container registry image
        run: |
          docker tag ghcr.io/${{ env.GHCR_IO_REPO }}/github-actions-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} ghcr.io/${{ env.GHCR_IO_REPO }}/github-actions-tidyverse:latest
          docker push ghcr.io/${{ env.GHCR_IO_REPO }}/github-actions-tidyverse:latest
      - name: Pull aws-lambda-tidyverse AWS ECR image
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/aws-lambda-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} 
      - name: Tag and push aws-lambda-tidyverse AWS ECR image
        run: |
          docker tag ${{ steps.login-ecr.outputs.registry }}/aws-lambda-tidyverse:${{ env.FAASR_VERSION }}-${{ env.TAG_SUFFIX }} ${{ steps.login-ecr.outputs.registry }}/aws-lambda-tidyverse:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/aws-lambda-tidyverse:latest
      - name: Pull custom github-actions-faasr Docker hub image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-faasr:${{ env.FAASR_TAG }}-${{ env.TAG_SUFFIX }}
      - name: Tag and push github-actions-tidyverse Github Container registry image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-faasr:${{ env.FAASR_TAG }}-${{ env.TAG_SUFFIX }} ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-faasr:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-faasr:latest

          
